###### Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.

Label Encoding apply on ordinal and nominal categorical variables. <br>Ordinal Encoding apply on ordinal categorical variables.

Assume there is a dataset where we have the Academic qualification of a group or Corporate position of a group of employees. There clearly we can have a order among the variable. There we can apply Ordinal Encodng.

In the same data dataset we have the provinces of their residance. As we can not put an order among the provinces we go for label encoding.

###### Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

Target-guided ordinal encoding involves replacing the categories in the categorical variable with ordinal numbers that are based on the relationship between the category and the target variable. The encoding process involves sorting the categories based on the mean of the target variable for each category and then assigning a numerical value to each category based on its rank.

This encoding technique can be used in various machine learning tasks, such as regression, classification, and ranking problems. It can also be useful in cases where the categorical variable has a high cardinality, meaning that it has many unique values.

###### Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

Covariance is a measure of the relationship between two random variables and to what extent, they change together. Or we can say, in other words, it defines the changes between the two variables, such that change in one variable is equal to change in another variable.

Feature selection involves understanding the relationships between input features, while dimensionality reduction techniques like Principal Component Analysis (PCA) use covariance to determine the most informative directions.

COV(x,y) = sum((x-meanX)(y-meanY))/N

###### Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

In [1]:
import pandas as pd
from  sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df = pd.DataFrame(
    {
        'color' : ['red','green','blue'],
        'size' : ['small', 'medium', 'large'],
        'material' : ['wood', 'metal', 'plastic']
    }
)
df

color    size material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [6]:
encoder.fit_transform(df[['color']]) # sorted all the unique color data and assign their position in array as their encoded data

C:\Users\prita\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0])

In [8]:
encoder.fit_transform(df[['size']]) # sorted all the unique size data and assign their position in array as their encoded data

C:\Users\prita\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0])

In [9]:
encoder.fit_transform(df[['material']]) # sorted all the unique material data and assign their position in array as their encoded data

C:\Users\prita\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1])

###### Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [2]:
import numpy as np
import pandas as pd

data = {
    'Age'  : [27,30,40,45,50],
    'Income' : [100000, 30000, 250000,150000,300000 ],
    'Edu_level' : [3,1,4,2,3] #education lavel is encoded as HS<B<M<Phd 
}
df= pd.DataFrame(data)
df

Age  Income  Edu_level
0   27  100000          3
1   30   30000          1
2   40  250000          4
3   45  150000          2
4   50  300000          3

In [4]:
df.cov()

Age        Income  Edu_level
Age            95.30  8.695000e+05       2.95
Income     869500.00  1.203000e+10   93000.00
Edu_level       2.95  9.300000e+04       1.30

###### Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?

For:

    Gender - One Hot encoding as there is only 2 category of data
    Education Level - Ordinal Encoding as High School<Bachelor's<Master's<PhD
    Employment Status - One Hot encoding as there is only 3 category of data

###### Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.

In [10]:
data = {
    'Temp'  : np.random.randint(0,100,(10)),
    'Humidity' : np.random.randint(50,100,(10)),
    'Weth_Cond' : np.random.randint(1,3,(10)), #lebel: (Sunny -1/Cloudy-2/Rainy-3) 
    'Wind_Dir' : np.random.randint(1,4,(10)) # (North - 1/South - 2/ East - 3/West - 4)
}

df = pd.DataFrame(data)

In [11]:
df

Temp  Humidity  Weth_Cond  Wind_Dir
0    49        95          1         1
1     0        95          2         3
2    43        60          2         2
3     9        88          1         2
4    35        68          2         2
5    43        93          2         2
6    22        98          2         3
7    65        97          1         3
8    71        70          1         2
9    95        56          2         1

In [12]:
df.cov()

Temp    Humidity  Weth_Cond   Wind_Dir
Temp       835.288889 -251.888889  -2.355556 -11.133333
Humidity  -251.888889  275.111111  -2.444444   6.333333
Weth_Cond   -2.355556   -2.444444   0.266667   0.044444
Wind_Dir   -11.133333    6.333333   0.044444   0.544444

The -ve data shows the Negative Covariance and the Positive data shows positive covariance. From the table we can see, in-between

    Temp and (Humidity, Wether cond, wnid dir.) we have negative covariance
    Humidity and (Wether cond, wnid dir.) we have negative and positive covariance
    Wether cond and wnid dir. we have very small positive covariance